version: "2"
services:
  nerves:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./firmware:/opt/app
      - ./keyfix.sh:/usr/local/bin/keyfix.sh
      - ~/.nerves/:/root/.nerves
      - ~/.ssh/:/tmp/.ssh
      - /dev/sdb:/dev/sdb
    env_file: .env
    privileged: true
    entrypoint: /usr/local/bin/keyfix.sh
    working_dir: /opt/app
    stdin_open: true
